language: rust
rust:
  - stable
  - nightly
script:
  - cargo test --verbose

jobs:
  include:
    - stage: deploy
      rust: stable
      script: |
        cargo doc &&
        echo "<meta http-equiv=refresh content=0;url=`basename ${TRAVIS_REPO_SLUG}`/index.html>" > target/doc/index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: target/doc
        target_branch: gh-pages
        on:
          branch: master
